---
title: "Final Project"
author: "Nichole Yao"
date: "12/3/2017"
output: html_document
---
---
title: "Mini Project#4"
output: github_document
---
```{r, message=FALSE}
library(mdsr)
library(RMySQL)
library(dplyr)
db <- dbConnect_scidb(dbname = "imdb")
big_data<- db%>% 
dbGetQuery("SELECT n.name, n.id AS person_id, n.gender, ci.movie_id, t.production_year
FROM imdb.person_info pi
JOIN name n ON pi.person_id = n.id
JOIN cast_info ci ON ci.person_id = n.id
JOIN movie_info mi ON ci.movie_id = mi.movie_id
JOIN title t ON t.id = mi.movie_id
AND ci.role_id = 3
AND mi.info_type_id = 3 
AND t.kind_id = 1
HAVING t.production_year <2017;")

big_data1<- distinct(big_data)
big_data2 <- na.omit(big_data1)
big_data3<- big_data2 %>%
  mutate(decade = 10 * floor(production_year / 10))%>%
  select(decade,gender) %>%
  group_by(decade, gender) %>% 
  dplyr::summarize(N = n(), male = sum(ifelse(gender =="m",1,0)),
female = sum(ifelse(gender =="f",1,0)))

big_data4<- big_data3 %>%
  group_by(decade) %>%
  dplyr::summarize(N=n(),m = sum(male), f = sum(female))

```
#percentage graph
```{r}
d_percentage<- big_data4 %>%
  mutate(total = m+f,
  male_percentage = m*100/total, 
  female_percentage = f*100/total) %>%
  select(male_percentage, female_percentage, decade, total) %>% 
  tidyr::gather(key = "gender", value = "percentage", -decade, -total)
d_percentage

d_percentage <- ddply(d_percentage, .(decade),
                transform, pos = cumsum(percentage) - (0.5 * percentage))
p3 <- ggplot() + geom_bar(aes(y = floor(percentage), x = decade, fill = gender), data = d_percentage, stat="identity") + 
geom_text(data=d_percentage, aes(x = decade, y = pos, label = paste0(floor(percentage),"%")), size=4) + 
theme(legend.position="bottom", legend.direction="horizontal",
                  legend.title = element_blank()) + 
                  scale_x_continuous(breaks=seq(1890,2010,10))
p3
```


```{r setup, include=FALSE}
library(mdsr)
library(RMySQL)
library(dplyr)
db <- dbConnect_scidb(dbname = "imdb")
big_data<- db%>% 
dbGetQuery("SELECT DISTINCT n.name, n.id, n.gender, ci.movie_id, t.production_year
FROM imdb.person_info pi
JOIN name n ON pi.person_id = n.id
JOIN cast_info ci ON ci.person_id = n.id
JOIN movie_info mi ON ci.movie_id = mi.movie_id
JOIN title t ON t.id = mi.movie_id
WHERE ci.role_id = 3
AND t.kind_id = 1;")
big_data
# AND mi.info_type_id = 3 
# AND mi.info IN ('Romance', 'Comedy','Horror','Action')
distinct(big_data)
big_data2<- na.omit(big_data)
big_data3<- big_data2 %>%
  select(production_year,gender,movie_id)%>%
  filter(production_year < 2018, production_year >1996)%>%
  group_by(production_year,gender)%>%
  summarize(Count = n())
#male = sum(ifelse(gender =="m",1,0)),
#female = sum(ifelse(gender =="f",1,0))
big_data4<- big_data3 %>%
  group_by(production_year)%>%
  summarize(m=sum(male),
            f=sum(female))

 
library(tidyverse)
ggplot(big_data3, aes(factor(production_year), Count, fill = gender)) + 
geom_bar(stat="identity", position = "dodge",width=.55)
```

--